source 'https://github.com/CocoaPods/Specs.git'


target 'LiveEB_Demo' do
 platform :ios, '9.0'

 ####LiveEB_IOS 封装了webrtc接口
 #####LiveEB_IOS内部使用定制版webrtc TWebRTC 参考 https://github.com/tencentyun/TCWebRTC编译
 
 pod 'TWebRTC', :git=>'https://github.com/tencentyun/TWebRTC-IOS-SDK.git' , :tag => '1.3.3'
######
 pod 'LiveEB_IOS', :git=>'https://github.com/tencentyun/leb-ios-sdk.git' , :tag => '1.10.5'
##
# pod 'TWebRTC', :path=>'./../../WebRTC'
# pod 'LiveEB_IOS', :path=>'./../../SRC/LiveEB_IOS'
  
end
