source 'https://github.com/CocoaPods/Specs.git'


target 'LiveEB_Demo' do
 platform :ios, '9.0'
 pod 'LiveEB_IOS', :git=>'https://github.com/tencentyun/leb-ios-sdk.git' , :tag => '1.0.2'

 #pod 'LiveEB_IOS', :path=>'./../tencent/leb-ios-sdk'
end
